version: "3"
services:
        backend:
                build: ./Backend
                ports:
                        - 8080:8080
                          
        frontend:
                build: ./Frontend
                ports:
                        - 8501:8501                

